name 'apache2_configure_as_proxy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures apache2_configure_as_proxy'
long_description 'Installs/Configures apache2_configure_as_proxy'
version '0.1.0'
