name 'odoo_v9_install'
maintainer 'Michael Doederlein'
maintainer_email 'michael.doederlein@cloud-logic.net'
license 'all_rights'
description 'Installs/Configures odoo_v9_install'
long_description 'Installs/Configures odoo_v9_install'
version '0.1.0'
depends 'apt'
depends 'postgresql', '~> 4.0.4'
#depends 'nodejs', '~> 2.4.4'
