name 'opsworks_test1'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures opsworks_test1'
long_description 'Installs/Configures opsworks_test1'
version '0.1.0'
